import type { Metadata } from "next";
import { Geist, Playfair_Display, Share_Tech, Inter } from "next/font/google";
import "@/app/globals.css";
import Navbar from "../Components/Navbar";
import FooterSection from "../Components/FooterSection";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const playFairFonts = Playfair_Display({
  variable: "--font-playfair-display",
  weight: "500",
  display: "swap",
  subsets: ["latin"],
});

const shareTechFont = Share_Tech({
  weight: "400",
  display: "swap",
  subsets: ["latin"],
});

const inter = Inter({
  weight: "400",
  display: "swap",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function InnerPagesLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html>
      <body className={inter.className}>
        <Navbar />

        {children}
        <FooterSection />
      </body>
    </html>
  );
}
